version: 1
datastore:
  filename: /data/anomaly.sqlite # ONLY CHANGE THIS LINE
  hostname: acit3855group4kafka.eastus2.cloudapp.azure.com
  port: 3306
  user: superbaddefault
  password: superbaddefault
  db: events
scheduler:
  period_sec: 5
eventstore:
  url: http://acit3855group4kafka.eastus2.cloudapp.azure.com/storage
events:
  hostname: acit3855group4kafka.eastus2.cloudapp.azure.com
  port: 9092
  topic: events
kafka:
  hosts: "acit3855group4kafka.eastus2.cloudapp.azure.com:9092"
  topic: "events"
  max_retries: 5
  retry_interval: 10
anomaly:
  thress1: 50
  thress2: 8